-- ==============================================================================
-- MÓDULO 1: GOVERNANÇA E ADMINISTRAÇÃO
-- ==============================================================================

CREATE TABLE configuracoes_empresa (
    id_config INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_fantasia VARCHAR(150) NOT NULL,
    cnpj VARCHAR(20) NOT NULL,
    endereco_completo TEXT,
    telefone VARCHAR(20),
    termos_garantia_padrao TEXT,
    dicas_uso_padrao TEXT
);

CREATE TABLE usuarios (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil enum_perfil_usuario NOT NULL,
    status enum_status_usuario DEFAULT 'Ativo',
	token_recuperacao VARCHAR(255),        
    data_expiracao_token TIMESTAMP,       
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE lembretes (
    id_lembrete INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL,
    titulo VARCHAR(150) NOT NULL,
    descricao TEXT,
    data_hora_lembrete TIMESTAMP NOT NULL,
    prioridade enum_prioridade_lembrete,
    status enum_status_lembrete DEFAULT 'Pendente',
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE log_auditoria (
    id_log INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_tabela VARCHAR(100) NOT NULL,
    acao enum_tipo_acao_auditoria NOT NULL,
    dados_antigos TEXT,
    dados_novos TEXT,
    id_usuario INT, 
    data_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE SET NULL
);

-- ==============================================================================
-- MÓDULO 2: RELACIONAMENTO (CRM)
-- ==============================================================================

CREATE TABLE clientes (
    id_cliente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    telefone_whatsapp VARCHAR(20) NOT NULL,
    cpf_cnpj VARCHAR(20),
    endereco TEXT,
    data_cadastro DATE DEFAULT CURRENT_DATE
);

CREATE TABLE equipamentos (
    id_equipamento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT NOT NULL,
    tipo_aparelho VARCHAR(50) NOT NULL, 
    marca VARCHAR(50),
    modelo VARCHAR(100),
    numero_serie VARCHAR(100),
    observacoes TEXT,
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE CASCADE
);

-- ==============================================================================
-- MÓDULO 4: ESTOQUE (SUPRIMENTOS)
-- ==============================================================================

CREATE TABLE fornecedores (
    id_fornecedor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    razao_social VARCHAR(150) NOT NULL,
    nome_fantasia VARCHAR(150),
    cnpj VARCHAR(20),
    telefone_contato VARCHAR(20),
    email VARCHAR(100)
);

CREATE TABLE produtos_pecas (
    id_produto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    categoria VARCHAR(50),
    condicao enum_condicao_produto NOT NULL, 
    custo DECIMAL(10,2) NOT NULL,
    preco_venda DECIMAL(10,2) NOT NULL,
    saldo_atual INT DEFAULT 0,
    estoque_minimo INT DEFAULT 0
);

CREATE TABLE movimentacoes_estoque (
    id_movimentacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto INT NOT NULL,
    tipo_movimentacao enum_tipo_movimentacao NOT NULL, 
    quantidade INT NOT NULL,
    data TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(255),
    id_usuario INT NOT NULL,
    id_fornecedor INT, 
    FOREIGN KEY (id_produto) REFERENCES produtos_pecas(id_produto) ON DELETE RESTRICT,
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE RESTRICT,
    FOREIGN KEY (id_fornecedor) REFERENCES fornecedores(id_fornecedor) ON DELETE SET NULL
);

-- ==============================================================================
-- MÓDULO 3: OPERACIONAL 
-- ==============================================================================

CREATE TABLE servicos (
    id_servico INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    valor_padrao DECIMAL(10,2) NOT NULL,
    tempo_estimado VARCHAR(50)
);

CREATE TABLE ordens_servico (
    id_os INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_equipamento INT NOT NULL,
    data_entrada TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    problema_relatado TEXT NOT NULL,
    estado_carcaca TEXT,
    estado_tela TEXT,
    estado_bateria TEXT,
    estado_componentes_internos TEXT,
    laudo_tecnico TEXT,
    endereco_visita TEXT, 
    status_os VARCHAR(50) DEFAULT 'Orçamento Pendente',
    data_validade_orcamento DATE,
    valor_desconto DECIMAL(10,2) DEFAULT 0.00,
    motivo_desconto VARCHAR(150),
    valor_total DECIMAL(10,2) DEFAULT 0.00,
    valor_pago DECIMAL(10,2) DEFAULT 0.00,
    data_entrega TIMESTAMP,
    FOREIGN KEY (id_equipamento) REFERENCES equipamentos(id_equipamento) ON DELETE RESTRICT
);

CREATE TABLE os_itens (
    id_item_os INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_os INT NOT NULL,
    id_produto INT, 
    id_servico INT, 
    nome_opcao VARCHAR(50) DEFAULT 'Única',
    aprovado BOOLEAN DEFAULT TRUE,
    quantidade INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (id_os) REFERENCES ordens_servico(id_os) ON DELETE CASCADE,
    FOREIGN KEY (id_produto) REFERENCES produtos_pecas(id_produto) ON DELETE RESTRICT,
    FOREIGN KEY (id_servico) REFERENCES servicos(id_servico) ON DELETE RESTRICT
);


CREATE TABLE os_fotos (
    id_foto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_os INT NOT NULL,
    nome_foto VARCHAR(255) NOT NULL,
    tipo_foto enum_tipo_foto, 
    data_upload TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_os) REFERENCES ordens_servico(id_os) ON DELETE CASCADE
);

-- ==============================================================================
-- MÓDULO 5: COMERCIAL E FINANCEIRO
-- ==============================================================================

CREATE TABLE vendas (
    id_venda INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INT, 
    data_venda TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    valor_total DECIMAL(10,2) NOT NULL,
    forma_pagamento VARCHAR(50),
    status enum_status_venda DEFAULT 'Concluída',
    FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente) ON DELETE SET NULL
);

CREATE TABLE vendas_itens (
    id_item_venda INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda INT NOT NULL,
    id_produto INT, 
    id_servico INT, 
    quantidade INT NOT NULL,
    valor_unitario DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (id_venda) REFERENCES vendas(id_venda) ON DELETE CASCADE,
    FOREIGN KEY (id_produto) REFERENCES produtos_pecas(id_produto) ON DELETE RESTRICT,
    FOREIGN KEY (id_servico) REFERENCES servicos(id_servico) ON DELETE RESTRICT
);

CREATE TABLE transacoes_financeiras (
    id_transacao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo enum_tipo_transacao NOT NULL, 
    origem VARCHAR(100) NOT NULL, 
    valor DECIMAL(10,2) NOT NULL,
    data_pagamento TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    forma_pagamento VARCHAR(50),
    id_os INT, 
    id_venda INT, 
    FOREIGN KEY (id_os) REFERENCES ordens_servico(id_os) ON DELETE SET NULL,
    FOREIGN KEY (id_venda) REFERENCES vendas(id_venda) ON DELETE SET NULL
);